### PR TITLE
Anshuman.md

### PR DESCRIPTION
**Pull request by anshuman725**

### CODE REVIEW

**Comment by vsasvipul0605** [comment]
What is this **Bot-Army** about??
What are you trying to provide with this organization?

**Comment by Yashank18** [comment]
This organization was made during my workshop on Open Source Contribution, all of the attendees get to be a part of it and we gonna be working on a project together. The details of the project will be out soon.
@vsasvipul0605

**Comment by vsasvipul0605** [comment]
Non-attendees will also get the chance or not?

**Comment by vsasvipul0605** [comment]
As I'm a newbie here and currently searching for different organizations to contribute.

**Comment by Yashank18** [comment]
They will get a chance once we announce our project. Anyone can work on opened issues and be a part of the community. 😃
@vsasvipul0605

**Pull request closed without merging**
